version: '2'
services:
  web: &app_base
    build:
      context: .
      dockerfile: "Dockerfile.dev"
    command: ["bundle", "exec", "rails", "s", "-p", "3000", "-b", "0.0.0.0"]
    env_file:
      - "./.env.dev"
    volumes:
      - .:/app
    volumes_from:
      - data
    ports:
      - "3000:3000"
    depends_on:
      - db
    tty: true
    stdin_open: true
  webpack:
    <<: *app_base
    command: "bin/webpack-dev-server"
    ports:
      - "3035:3035"
    depends_on:
      - web
    tty: false
    stdin_open: false
  db:
    image: mysql:5.7
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes_from:
      - data
    command: --innodb-use-native-aio=0 --ignore-db-dir=data
  data:
    image: "busybox"
    volumes:
      - mysql-data:/var/lib/mysql
      - bundle:/vendor/bundle
volumes:
  mysql-data:
    driver: local
  bundle:
    driver: local
